[tool.poetry]
name = "customer-onboarding-assistant"
version = "0.1.0"
description = "Project to showcase agentic paradigm on a customer onboarding assistant use case."
authors = ["Pierre Bittner <pierre@bittner.fr>"]
license = "Apache Licence"
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
langchain = "^0.3.9"
langgraph = "^0.2.53"
mistralai = "^1.2.3"
openai = "^1.55.2"
chromadb = "^0.5.20"
langchain-community = "^0.3.5"
langchain-openai = "^0.2.10"
langchain-mistralai = "^0.2.2"
langchain-chroma = "^0.1.4"
langsmith = "^0.1.147"
pytest = "^8.3.4"
bs4 = "^0.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
